# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_CONNECTIONRESPONSE_RESPONSECODE = descriptor.EnumDescriptor(
  name='ResponseCode',
  full_name='BasicProtobuf.ConnectionResponse.ResponseCode',
  filename='ResponseCode',
  values=[
    descriptor.EnumValueDescriptor(
      name='OK', index=0, number=200,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BadMessageFormatting', index=1, number=400,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UnknownService', index=2, number=404,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NotSupportedVersion', index=3, number=405,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='Timeout', index=4, number=408,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ProtocolError', index=5, number=410,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='InternalError', index=6, number=500,
      options=None,
      type=None),
  ],
  options=None,
)


_CONNECTIONRESPONSE = descriptor.Descriptor(
  name='ConnectionResponse',
  full_name='BasicProtobuf.ConnectionResponse',
  filename='basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='responseCode', full_name='BasicProtobuf.ConnectionResponse.responseCode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=200,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sessionId', full_name='BasicProtobuf.ConnectionResponse.sessionId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='BasicProtobuf.ConnectionResponse.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _CONNECTIONRESPONSE_RESPONSECODE,
  ],
  options=None)


_CONNECTIONRESPONSE.fields_by_name['responseCode'].enum_type = _CONNECTIONRESPONSE_RESPONSECODE

class ConnectionResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONNECTIONRESPONSE

