# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tts.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import basic_pb2
import ttsbackend_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tts.proto',
  package='TTS',
  serialized_pb='\n\ttts.proto\x12\x03TTS\x1a\x0b\x62\x61sic.proto\x1a\x10ttsbackend.proto\"\xb9\x01\n\x11\x43onnectionRequest\x12\x13\n\x0bserviceName\x18\x01 \x02(\t\x12\x0c\n\x04uuid\x18\x02 \x02(\t\x12\x1a\n\x0fprotocolVersion\x18\x03 \x01(\x05:\x01\x31\x12\x12\n\ndeviceName\x18\x04 \x01(\t\x12\x18\n\x10speechkitVersion\x18\x05 \x01(\t\x12\x0e\n\x06\x61piKey\x18\x06 \x01(\t\x12\x17\n\x0f\x61pplicationName\x18\x07 \x01(\t\x12\x0e\n\x06\x63oords\x18\x08 \x01(\t\"#\n\rParamsRequest\x12\x12\n\nlistVoices\x18\x01 \x01(\x08\"\xbc\x01\n\x0eParamsResponse\x12,\n\tvoiceList\x18\x01 \x03(\x0b\x32\x19.TTS.ParamsResponse.Voice\x1a|\n\x05Voice\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06gender\x18\x02 \x02(\x05\x12\x12\n\nlanguageId\x18\x03 \x02(\x05\x12\x19\n\x11initialSampleFreq\x18\x04 \x02(\x05\x12\x13\n\x0b\x64isplayName\x18\x05 \x01(\t\x12\x11\n\tcoreVoice\x18\x06 \x01(\x08\"\xa5\x03\n\x0fGenerateRequest\x12\x0c\n\x04lang\x18\x01 \x02(\t\x12\x0c\n\x04text\x18\x02 \x02(\t\x12\x13\n\x0b\x61pplication\x18\x03 \x02(\t\x12\x10\n\x08platform\x18\x04 \x02(\t\x12\r\n\x05voice\x18\x06 \x02(\t\x12\r\n\x05speed\x18\x1f \x01(\x02\x12\x0f\n\x07\x65motion\x18\n \x01(\t\x12\x33\n\x07quality\x18\x07 \x01(\x0e\x32\x1c.TTS.GenerateRequest.Quality:\x04High\x12\x30\n\x06\x66ormat\x18\x08 \x01(\x0e\x32\x1b.TTS.GenerateRequest.Format:\x03Spx\x12\x1e\n\x0frequireMetainfo\x18\x05 \x01(\x08:\x05\x66\x61lse\x12.\n\x17lowLevelGenerateRequest\x18\x1e \x01(\x0b\x32\r.TTS.Generate\x12\x16\n\x0espeed_obsolete\x18\t \x01(\t\x12\x0e\n\x06volume\x18  \x01(\x02\"\x1c\n\x07Quality\x12\x08\n\x04High\x10\x00\x12\x07\n\x03Low\x10\x01\"#\n\x06\x46ormat\x12\x07\n\x03Wav\x10\x00\x12\x07\n\x03Pcm\x10\x01\x12\x07\n\x03Spx\x10\x02')



_GENERATEREQUEST_QUALITY = _descriptor.EnumDescriptor(
  name='Quality',
  full_name='TTS.GenerateRequest.Quality',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='High', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Low', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=822,
  serialized_end=850,
)

_GENERATEREQUEST_FORMAT = _descriptor.EnumDescriptor(
  name='Format',
  full_name='TTS.GenerateRequest.Format',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Wav', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Pcm', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Spx', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=852,
  serialized_end=887,
)


_CONNECTIONREQUEST = _descriptor.Descriptor(
  name='ConnectionRequest',
  full_name='TTS.ConnectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serviceName', full_name='TTS.ConnectionRequest.serviceName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='TTS.ConnectionRequest.uuid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protocolVersion', full_name='TTS.ConnectionRequest.protocolVersion', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceName', full_name='TTS.ConnectionRequest.deviceName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speechkitVersion', full_name='TTS.ConnectionRequest.speechkitVersion', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='apiKey', full_name='TTS.ConnectionRequest.apiKey', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='applicationName', full_name='TTS.ConnectionRequest.applicationName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coords', full_name='TTS.ConnectionRequest.coords', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=235,
)


_PARAMSREQUEST = _descriptor.Descriptor(
  name='ParamsRequest',
  full_name='TTS.ParamsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='listVoices', full_name='TTS.ParamsRequest.listVoices', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=237,
  serialized_end=272,
)


_PARAMSRESPONSE_VOICE = _descriptor.Descriptor(
  name='Voice',
  full_name='TTS.ParamsResponse.Voice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='TTS.ParamsResponse.Voice.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='TTS.ParamsResponse.Voice.gender', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='languageId', full_name='TTS.ParamsResponse.Voice.languageId', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initialSampleFreq', full_name='TTS.ParamsResponse.Voice.initialSampleFreq', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='displayName', full_name='TTS.ParamsResponse.Voice.displayName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coreVoice', full_name='TTS.ParamsResponse.Voice.coreVoice', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=339,
  serialized_end=463,
)

_PARAMSRESPONSE = _descriptor.Descriptor(
  name='ParamsResponse',
  full_name='TTS.ParamsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='voiceList', full_name='TTS.ParamsResponse.voiceList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PARAMSRESPONSE_VOICE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=275,
  serialized_end=463,
)


_GENERATEREQUEST = _descriptor.Descriptor(
  name='GenerateRequest',
  full_name='TTS.GenerateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lang', full_name='TTS.GenerateRequest.lang', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='TTS.GenerateRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='application', full_name='TTS.GenerateRequest.application', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='platform', full_name='TTS.GenerateRequest.platform', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voice', full_name='TTS.GenerateRequest.voice', index=4,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='TTS.GenerateRequest.speed', index=5,
      number=31, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='emotion', full_name='TTS.GenerateRequest.emotion', index=6,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quality', full_name='TTS.GenerateRequest.quality', index=7,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='format', full_name='TTS.GenerateRequest.format', index=8,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requireMetainfo', full_name='TTS.GenerateRequest.requireMetainfo', index=9,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lowLevelGenerateRequest', full_name='TTS.GenerateRequest.lowLevelGenerateRequest', index=10,
      number=30, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed_obsolete', full_name='TTS.GenerateRequest.speed_obsolete', index=11,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='volume', full_name='TTS.GenerateRequest.volume', index=12,
      number=32, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GENERATEREQUEST_QUALITY,
    _GENERATEREQUEST_FORMAT,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=466,
  serialized_end=887,
)

_PARAMSRESPONSE_VOICE.containing_type = _PARAMSRESPONSE;
_PARAMSRESPONSE.fields_by_name['voiceList'].message_type = _PARAMSRESPONSE_VOICE
_GENERATEREQUEST.fields_by_name['quality'].enum_type = _GENERATEREQUEST_QUALITY
_GENERATEREQUEST.fields_by_name['format'].enum_type = _GENERATEREQUEST_FORMAT
_GENERATEREQUEST.fields_by_name['lowLevelGenerateRequest'].message_type = ttsbackend_pb2._GENERATE
_GENERATEREQUEST_QUALITY.containing_type = _GENERATEREQUEST;
_GENERATEREQUEST_FORMAT.containing_type = _GENERATEREQUEST;
DESCRIPTOR.message_types_by_name['ConnectionRequest'] = _CONNECTIONREQUEST
DESCRIPTOR.message_types_by_name['ParamsRequest'] = _PARAMSREQUEST
DESCRIPTOR.message_types_by_name['ParamsResponse'] = _PARAMSRESPONSE
DESCRIPTOR.message_types_by_name['GenerateRequest'] = _GENERATEREQUEST

class ConnectionRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONNECTIONREQUEST

  # @@protoc_insertion_point(class_scope:TTS.ConnectionRequest)

class ParamsRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARAMSREQUEST

  # @@protoc_insertion_point(class_scope:TTS.ParamsRequest)

class ParamsResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Voice(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PARAMSRESPONSE_VOICE

    # @@protoc_insertion_point(class_scope:TTS.ParamsResponse.Voice)
  DESCRIPTOR = _PARAMSRESPONSE

  # @@protoc_insertion_point(class_scope:TTS.ParamsResponse)

class GenerateRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GENERATEREQUEST

  # @@protoc_insertion_point(class_scope:TTS.GenerateRequest)


# @@protoc_insertion_point(module_scope)
