# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_CONNECTIONREQUEST = descriptor.Descriptor(
  name='ConnectionRequest',
  full_name='VoiceProxyProtobuf.ConnectionRequest',
  filename='voiceproxy.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='protocolVersion', full_name='VoiceProxyProtobuf.ConnectionRequest.protocolVersion', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='speechkitVersion', full_name='VoiceProxyProtobuf.ConnectionRequest.speechkitVersion', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='serviceName', full_name='VoiceProxyProtobuf.ConnectionRequest.serviceName', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='uuid', full_name='VoiceProxyProtobuf.ConnectionRequest.uuid', index=3,
      number=4, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='apiKey', full_name='VoiceProxyProtobuf.ConnectionRequest.apiKey', index=4,
      number=5, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='applicationName', full_name='VoiceProxyProtobuf.ConnectionRequest.applicationName', index=5,
      number=6, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='device', full_name='VoiceProxyProtobuf.ConnectionRequest.device', index=6,
      number=7, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='coords', full_name='VoiceProxyProtobuf.ConnectionRequest.coords', index=7,
      number=8, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='topic', full_name='VoiceProxyProtobuf.ConnectionRequest.topic', index=8,
      number=9, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lang', full_name='VoiceProxyProtobuf.ConnectionRequest.lang', index=9,
      number=10, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='format', full_name='VoiceProxyProtobuf.ConnectionRequest.format', index=10,
      number=11, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='punctuation', full_name='VoiceProxyProtobuf.ConnectionRequest.punctuation', index=11,
      number=12, type=8, cpp_type=7, label=1,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ADDDATA = descriptor.Descriptor(
  name='AddData',
  full_name='VoiceProxyProtobuf.AddData',
  filename='voiceproxy.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='audioData', full_name='VoiceProxyProtobuf.AddData.audioData', index=0,
      number=1, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lastChunk', full_name='VoiceProxyProtobuf.AddData.lastChunk', index=1,
      number=2, type=8, cpp_type=7, label=2,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_WORD = descriptor.Descriptor(
  name='Word',
  full_name='VoiceProxyProtobuf.Word',
  filename='voiceproxy.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='confidence', full_name='VoiceProxyProtobuf.Word.confidence', index=0,
      number=1, type=2, cpp_type=6, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='VoiceProxyProtobuf.Word.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RESULT = descriptor.Descriptor(
  name='Result',
  full_name='VoiceProxyProtobuf.Result',
  filename='voiceproxy.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='confidence', full_name='VoiceProxyProtobuf.Result.confidence', index=0,
      number=1, type=2, cpp_type=6, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='words', full_name='VoiceProxyProtobuf.Result.words', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='normalized', full_name='VoiceProxyProtobuf.Result.normalized', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ADDDATARESPONSE = descriptor.Descriptor(
  name='AddDataResponse',
  full_name='VoiceProxyProtobuf.AddDataResponse',
  filename='voiceproxy.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='responseCode', full_name='VoiceProxyProtobuf.AddDataResponse.responseCode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=200,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='recognition', full_name='VoiceProxyProtobuf.AddDataResponse.recognition', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endOfUtt', full_name='VoiceProxyProtobuf.AddDataResponse.endOfUtt', index=2,
      number=3, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='messagesCount', full_name='VoiceProxyProtobuf.AddDataResponse.messagesCount', index=3,
      number=4, type=5, cpp_type=1, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import basic_pb2

_RESULT.fields_by_name['words'].message_type = _WORD
_ADDDATARESPONSE.fields_by_name['responseCode'].enum_type = basic_pb2._CONNECTIONRESPONSE_RESPONSECODE
_ADDDATARESPONSE.fields_by_name['recognition'].message_type = _RESULT

class ConnectionRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONNECTIONREQUEST

class AddData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDDATA

class Word(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORD

class Result(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESULT

class AddDataResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDDATARESPONSE

