# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voiceproxy.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import basic_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='voiceproxy.proto',
  package='VoiceProxyProtobuf',
  serialized_pb='\n\x10voiceproxy.proto\x12\x12VoiceProxyProtobuf\x1a\x0b\x62\x61sic.proto\"\x81\x01\n\x0cMusicRequest\x12\x46\n\x11musicProxyOptions\x18\x01 \x03(\x0b\x32+.VoiceProxyProtobuf.MusicRequest.MusicParam\x1a)\n\nMusicParam\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"\xde\x02\n\x11\x43onnectionRequest\x12\x1a\n\x0fprotocolVersion\x18\x01 \x01(\x05:\x01\x31\x12\x18\n\x10speechkitVersion\x18\x02 \x02(\t\x12\x13\n\x0bserviceName\x18\x03 \x02(\t\x12\x0c\n\x04uuid\x18\x04 \x02(\t\x12\x0e\n\x06\x61piKey\x18\x05 \x02(\t\x12\x17\n\x0f\x61pplicationName\x18\x06 \x02(\t\x12\x0e\n\x06\x64\x65vice\x18\x07 \x02(\t\x12\x0e\n\x06\x63oords\x18\x08 \x02(\t\x12\r\n\x05topic\x18\t \x02(\t\x12\x0c\n\x04lang\x18\n \x02(\t\x12\x0e\n\x06\x66ormat\x18\x0b \x02(\t\x12\x19\n\x0bpunctuation\x18\x0c \x01(\x08:\x04true\x12\x36\n\x0cmusicRequest\x18\x11 \x01(\x0b\x32 .VoiceProxyProtobuf.MusicRequest\x12\'\n\x18\x64isableAntimatNormalizer\x18\x12 \x01(\x08:\x05\x66\x61lse\"/\n\x07\x41\x64\x64\x44\x61ta\x12\x11\n\taudioData\x18\x01 \x01(\x0c\x12\x11\n\tlastChunk\x18\x02 \x02(\x08\")\n\x04Word\x12\x12\n\nconfidence\x18\x01 \x02(\x02\x12\r\n\x05value\x18\x02 \x02(\t\"Y\n\x06Result\x12\x12\n\nconfidence\x18\x01 \x02(\x02\x12\'\n\x05words\x18\x02 \x03(\x0b\x32\x18.VoiceProxyProtobuf.Word\x12\x12\n\nnormalized\x18\x03 \x01(\t\"\xd7\x01\n\x0f\x41\x64\x64\x44\x61taResponse\x12\x44\n\x0cresponseCode\x18\x01 \x02(\x0e\x32..BasicProtobuf.ConnectionResponse.ResponseCode\x12/\n\x0brecognition\x18\x02 \x03(\x0b\x32\x1a.VoiceProxyProtobuf.Result\x12\x17\n\x08\x65ndOfUtt\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x18\n\rmessagesCount\x18\x04 \x01(\x05:\x01\x31\x12\x1a\n\x12musicProxyResponse\x18\x05 \x01(\t')




_MUSICREQUEST_MUSICPARAM = _descriptor.Descriptor(
  name='MusicParam',
  full_name='VoiceProxyProtobuf.MusicRequest.MusicParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='VoiceProxyProtobuf.MusicRequest.MusicParam.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='VoiceProxyProtobuf.MusicRequest.MusicParam.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=142,
  serialized_end=183,
)

_MUSICREQUEST = _descriptor.Descriptor(
  name='MusicRequest',
  full_name='VoiceProxyProtobuf.MusicRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='musicProxyOptions', full_name='VoiceProxyProtobuf.MusicRequest.musicProxyOptions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MUSICREQUEST_MUSICPARAM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=54,
  serialized_end=183,
)


_CONNECTIONREQUEST = _descriptor.Descriptor(
  name='ConnectionRequest',
  full_name='VoiceProxyProtobuf.ConnectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocolVersion', full_name='VoiceProxyProtobuf.ConnectionRequest.protocolVersion', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speechkitVersion', full_name='VoiceProxyProtobuf.ConnectionRequest.speechkitVersion', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serviceName', full_name='VoiceProxyProtobuf.ConnectionRequest.serviceName', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='VoiceProxyProtobuf.ConnectionRequest.uuid', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='apiKey', full_name='VoiceProxyProtobuf.ConnectionRequest.apiKey', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='applicationName', full_name='VoiceProxyProtobuf.ConnectionRequest.applicationName', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device', full_name='VoiceProxyProtobuf.ConnectionRequest.device', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coords', full_name='VoiceProxyProtobuf.ConnectionRequest.coords', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topic', full_name='VoiceProxyProtobuf.ConnectionRequest.topic', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lang', full_name='VoiceProxyProtobuf.ConnectionRequest.lang', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='format', full_name='VoiceProxyProtobuf.ConnectionRequest.format', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='punctuation', full_name='VoiceProxyProtobuf.ConnectionRequest.punctuation', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='musicRequest', full_name='VoiceProxyProtobuf.ConnectionRequest.musicRequest', index=12,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disableAntimatNormalizer', full_name='VoiceProxyProtobuf.ConnectionRequest.disableAntimatNormalizer', index=13,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=186,
  serialized_end=536,
)


_ADDDATA = _descriptor.Descriptor(
  name='AddData',
  full_name='VoiceProxyProtobuf.AddData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='audioData', full_name='VoiceProxyProtobuf.AddData.audioData', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastChunk', full_name='VoiceProxyProtobuf.AddData.lastChunk', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=538,
  serialized_end=585,
)


_WORD = _descriptor.Descriptor(
  name='Word',
  full_name='VoiceProxyProtobuf.Word',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confidence', full_name='VoiceProxyProtobuf.Word.confidence', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='VoiceProxyProtobuf.Word.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=587,
  serialized_end=628,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='VoiceProxyProtobuf.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confidence', full_name='VoiceProxyProtobuf.Result.confidence', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='words', full_name='VoiceProxyProtobuf.Result.words', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normalized', full_name='VoiceProxyProtobuf.Result.normalized', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=630,
  serialized_end=719,
)


_ADDDATARESPONSE = _descriptor.Descriptor(
  name='AddDataResponse',
  full_name='VoiceProxyProtobuf.AddDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='VoiceProxyProtobuf.AddDataResponse.responseCode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=200,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recognition', full_name='VoiceProxyProtobuf.AddDataResponse.recognition', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='endOfUtt', full_name='VoiceProxyProtobuf.AddDataResponse.endOfUtt', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='messagesCount', full_name='VoiceProxyProtobuf.AddDataResponse.messagesCount', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='musicProxyResponse', full_name='VoiceProxyProtobuf.AddDataResponse.musicProxyResponse', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=722,
  serialized_end=937,
)

_MUSICREQUEST_MUSICPARAM.containing_type = _MUSICREQUEST;
_MUSICREQUEST.fields_by_name['musicProxyOptions'].message_type = _MUSICREQUEST_MUSICPARAM
_CONNECTIONREQUEST.fields_by_name['musicRequest'].message_type = _MUSICREQUEST
_RESULT.fields_by_name['words'].message_type = _WORD
_ADDDATARESPONSE.fields_by_name['responseCode'].enum_type = basic_pb2._CONNECTIONRESPONSE_RESPONSECODE
_ADDDATARESPONSE.fields_by_name['recognition'].message_type = _RESULT
DESCRIPTOR.message_types_by_name['MusicRequest'] = _MUSICREQUEST
DESCRIPTOR.message_types_by_name['ConnectionRequest'] = _CONNECTIONREQUEST
DESCRIPTOR.message_types_by_name['AddData'] = _ADDDATA
DESCRIPTOR.message_types_by_name['Word'] = _WORD
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['AddDataResponse'] = _ADDDATARESPONSE

class MusicRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class MusicParam(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MUSICREQUEST_MUSICPARAM

    # @@protoc_insertion_point(class_scope:VoiceProxyProtobuf.MusicRequest.MusicParam)
  DESCRIPTOR = _MUSICREQUEST

  # @@protoc_insertion_point(class_scope:VoiceProxyProtobuf.MusicRequest)

class ConnectionRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONNECTIONREQUEST

  # @@protoc_insertion_point(class_scope:VoiceProxyProtobuf.ConnectionRequest)

class AddData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDDATA

  # @@protoc_insertion_point(class_scope:VoiceProxyProtobuf.AddData)

class Word(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORD

  # @@protoc_insertion_point(class_scope:VoiceProxyProtobuf.Word)

class Result(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESULT

  # @@protoc_insertion_point(class_scope:VoiceProxyProtobuf.Result)

class AddDataResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDDATARESPONSE

  # @@protoc_insertion_point(class_scope:VoiceProxyProtobuf.AddDataResponse)


# @@protoc_insertion_point(module_scope)
