// Code generated by protoc-gen-go.
// source: basic.proto
// DO NOT EDIT!

/*
Package BasicProtobuf is a generated protocol buffer package.

It is generated from these files:
	basic.proto

It has these top-level messages:
	ConnectionResponse
*/
package BasicProtobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ConnectionResponse_ResponseCode int32

const (
	ConnectionResponse_OK                   ConnectionResponse_ResponseCode = 200
	ConnectionResponse_BadMessageFormatting ConnectionResponse_ResponseCode = 400
	ConnectionResponse_UnknownService       ConnectionResponse_ResponseCode = 404
	ConnectionResponse_NotSupportedVersion  ConnectionResponse_ResponseCode = 405
	ConnectionResponse_Timeout              ConnectionResponse_ResponseCode = 408
	ConnectionResponse_ProtocolError        ConnectionResponse_ResponseCode = 410
	ConnectionResponse_InternalError        ConnectionResponse_ResponseCode = 500
	ConnectionResponse_InvalidKey           ConnectionResponse_ResponseCode = 429
	ConnectionResponse_InvalidRequestParams ConnectionResponse_ResponseCode = 406
)

var ConnectionResponse_ResponseCode_name = map[int32]string{
	200: "OK",
	400: "BadMessageFormatting",
	404: "UnknownService",
	405: "NotSupportedVersion",
	408: "Timeout",
	410: "ProtocolError",
	500: "InternalError",
	429: "InvalidKey",
	406: "InvalidRequestParams",
}
var ConnectionResponse_ResponseCode_value = map[string]int32{
	"OK": 200,
	"BadMessageFormatting": 400,
	"UnknownService":       404,
	"NotSupportedVersion":  405,
	"Timeout":              408,
	"ProtocolError":        410,
	"InternalError":        500,
	"InvalidKey":           429,
	"InvalidRequestParams": 406,
}

func (x ConnectionResponse_ResponseCode) Enum() *ConnectionResponse_ResponseCode {
	p := new(ConnectionResponse_ResponseCode)
	*p = x
	return p
}
func (x ConnectionResponse_ResponseCode) String() string {
	return proto.EnumName(ConnectionResponse_ResponseCode_name, int32(x))
}
func (x *ConnectionResponse_ResponseCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ConnectionResponse_ResponseCode_value, data, "ConnectionResponse_ResponseCode")
	if err != nil {
		return err
	}
	*x = ConnectionResponse_ResponseCode(value)
	return nil
}
func (ConnectionResponse_ResponseCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type ConnectionResponse struct {
	ResponseCode     *ConnectionResponse_ResponseCode `protobuf:"varint,1,req,name=responseCode,enum=BasicProtobuf.ConnectionResponse_ResponseCode" json:"responseCode,omitempty"`
	SessionId        *string                          `protobuf:"bytes,2,req,name=sessionId" json:"sessionId,omitempty"`
	Message          *string                          `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *ConnectionResponse) Reset()                    { *m = ConnectionResponse{} }
func (m *ConnectionResponse) String() string            { return proto.CompactTextString(m) }
func (*ConnectionResponse) ProtoMessage()               {}
func (*ConnectionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConnectionResponse) GetResponseCode() ConnectionResponse_ResponseCode {
	if m != nil && m.ResponseCode != nil {
		return *m.ResponseCode
	}
	return ConnectionResponse_OK
}

func (m *ConnectionResponse) GetSessionId() string {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return ""
}

func (m *ConnectionResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ConnectionResponse)(nil), "BasicProtobuf.ConnectionResponse")
	proto.RegisterEnum("BasicProtobuf.ConnectionResponse_ResponseCode", ConnectionResponse_ResponseCode_name, ConnectionResponse_ResponseCode_value)
}

var fileDescriptor0 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x8f, 0x31, 0x4e, 0xf3, 0x30,
	0x14, 0xc7, 0x95, 0x78, 0x88, 0xf2, 0xbe, 0xb4, 0x9f, 0x71, 0x19, 0xc2, 0x56, 0x75, 0xea, 0x94,
	0x81, 0x23, 0xb4, 0x80, 0x14, 0x55, 0x40, 0x95, 0x02, 0xbb, 0x9b, 0x3c, 0x2a, 0x8b, 0xc6, 0x2f,
	0xd8, 0x4e, 0x11, 0xb7, 0x60, 0x00, 0x84, 0xb8, 0x03, 0xa7, 0x80, 0x81, 0x03, 0x71, 0x00, 0x92,
	0x92, 0x81, 0x8a, 0xed, 0xef, 0x9f, 0xfd, 0xf3, 0xfb, 0x3f, 0xf8, 0xb7, 0x94, 0x56, 0xe5, 0x49,
	0x65, 0xc8, 0x91, 0xe8, 0x4d, 0xda, 0xc3, 0xbc, 0xcd, 0xcb, 0xfa, 0x7a, 0xf4, 0xe1, 0x83, 0x98,
	0x92, 0xd6, 0x98, 0x3b, 0x45, 0x3a, 0x43, 0x5b, 0x91, 0xb6, 0x28, 0x8e, 0x20, 0x32, 0x5d, 0x9e,
	0x52, 0x81, 0xb1, 0x37, 0xf4, 0xc7, 0xfd, 0xc3, 0x24, 0xd9, 0x91, 0x93, 0xbf, 0x62, 0x92, 0xfd,
	0xb2, 0xc4, 0x1e, 0x84, 0x16, 0xad, 0x6d, 0xee, 0xd3, 0x22, 0xf6, 0x9b, 0x2f, 0x42, 0xf1, 0x1f,
	0x82, 0xb2, 0x41, 0x72, 0x85, 0x31, 0x1b, 0x7a, 0xe3, 0x70, 0xf4, 0xee, 0x41, 0xb4, 0x23, 0x05,
	0xe0, 0x9f, 0xcf, 0xf8, 0xa7, 0x27, 0x0e, 0x60, 0x7f, 0x22, 0x8b, 0xd3, 0x9f, 0xd7, 0x27, 0x64,
	0x4a, 0xe9, 0x9c, 0xd2, 0x2b, 0xfe, 0xc0, 0xc4, 0x00, 0xfa, 0x97, 0xfa, 0x46, 0xd3, 0x9d, 0x5e,
	0xa0, 0xd9, 0xa8, 0x1c, 0xf9, 0x23, 0x13, 0x31, 0x0c, 0xce, 0xc8, 0x2d, 0xea, 0xaa, 0x22, 0xe3,
	0xb0, 0xb8, 0x42, 0xd3, 0x4e, 0xe6, 0x4f, 0x4c, 0x44, 0x10, 0x5c, 0xa8, 0x12, 0xa9, 0x76, 0xfc,
	0x85, 0x09, 0x01, 0xbd, 0xed, 0x06, 0x39, 0xad, 0x8f, 0x8d, 0x21, 0xc3, 0x5f, 0xb7, 0x2c, 0xd5,
	0x0e, 0x8d, 0x96, 0x1d, 0xfb, 0x62, 0x4d, 0x55, 0x48, 0xf5, 0x46, 0xae, 0x55, 0x31, 0xc3, 0x7b,
	0xfe, 0xc6, 0xda, 0x42, 0x1d, 0xc8, 0xf0, 0xb6, 0x46, 0xeb, 0xe6, 0xd2, 0xc8, 0xd2, 0xf2, 0x67,
	0xf6, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x49, 0xa0, 0xc3, 0x63, 0x01, 0x00, 0x00,
}
